title: Yet Another Translate Keyboard
description: One-tap inline translator iOS keyboard
theme: minima
url: "https://amin.benarieb.com"
baseurl: "/translatekb"

show_excerpts: false
header_pages:
  - index.md
  - privacy/index.md
